#!/bin/bash

runtest() {
  bash -c "$1 > my-$2 2> /dev/null"
  cmp $2 my-$2 > /dev/null
  if [ $? -eq 0 ]; then
    printf "passed: "
  else
    printf "FAILED: "
  fi
  printf "%s\n" "$1 > my-$2 2> /dev/null"
}

echo "Delete output files (my-out.*) from previous tests?"
echo "Press ctl-c to abort, any other key to delete my-out files & run tests"
read x
rm -f my-out?.*

runtest "./a1 < inv.1" out.inv1
runtest "./a1 < inv.2" out.inv2
runtest "./a1 < inv.3" out.inv3
runtest "./a1 < inv.4" out.inv4
